-- Supabase Consolidated Initialization Script
-- Project: AI Contract & Invoice Automation
-- Date: 2026-01-20

-- ==========================================
-- 1. EXTENSIONS & FUNCTIONS
-- ==========================================

-- Enable Catholic extensions if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to handle updated_at timestamps
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 2. TABLE DEFINITIONS
-- ==========================================

-- User Settings Table
CREATE TABLE IF NOT EXISTS user_settings (
  user_email TEXT PRIMARY KEY,
  user_id TEXT, -- For Supabase Auth UID mapping if available
  gemini_api_key TEXT,
  google_client_id TEXT,
  google_api_key TEXT,
  google_drive_folder_id TEXT,
  company_profile JSONB DEFAULT '{}'::jsonb,
  bank_info JSONB DEFAULT '{}'::jsonb,
  seal_url TEXT,
  party_b_info JSONB DEFAULT '{}'::jsonb,
  quick_access JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Contracts Table
CREATE TABLE IF NOT EXISTS contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  contract_number TEXT,
  title TEXT,
  party_a TEXT NOT NULL,
  party_b TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '提案中',
  storage_path TEXT,
  auto_renewal BOOLEAN DEFAULT FALSE,
  deadline DATE,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Companies Table
CREATE TABLE IF NOT EXISTS companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  name TEXT NOT NULL,
  postal_code TEXT,
  address TEXT,
  building TEXT,
  president_title TEXT,
  president_name TEXT,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  position TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Templates Table
CREATE TABLE IF NOT EXISTS templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email TEXT NOT NULL,
  name TEXT NOT NULL,
  party_a TEXT,
  party_b TEXT,
  address_a TEXT,
  address_b TEXT,
  president_position_a TEXT,
  president_name_a TEXT,
  president_position_b TEXT,
  president_name_b TEXT,
  content TEXT,
  saved_at TIMESTAMPTZ DEFAULT NOW()
);

-- Billings (Invoices) Table
CREATE TABLE IF NOT EXISTS billings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id BIGINT REFERENCES contracts(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL,
  invoice_number TEXT,
  issue_date DATE,
  payment_deadline DATE,
  items JSONB DEFAULT '[]'::jsonb,
  client_info JSONB DEFAULT '{}'::jsonb,
  subtotal NUMERIC DEFAULT 0,
  tax_total JSONB DEFAULT '{"tax8": 0, "tax10": 0}'::jsonb,
  total NUMERIC DEFAULT 0,
  amount NUMERIC DEFAULT 0, -- Duplicate of total for backward compatibility
  status TEXT DEFAULT 'Planned', -- Planned, Approved, Sent, Paid
  pdf_url TEXT,
  payment_date DATE, -- Date when payment was received
  is_recurring BOOLEAN DEFAULT FALSE,
  recurring_interval TEXT, -- monthly, quarterly, yearly
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_contracts_user_email ON contracts(user_email);
CREATE INDEX IF NOT EXISTS idx_contracts_contract_number ON contracts(contract_number);
CREATE INDEX IF NOT EXISTS idx_companies_user_email ON companies(user_email);
CREATE INDEX IF NOT EXISTS idx_templates_user_email ON templates(user_email);
CREATE INDEX IF NOT EXISTS idx_billings_user_email ON billings(user_email);
CREATE INDEX IF NOT EXISTS idx_billings_contract_id ON billings(contract_id);
CREATE INDEX IF NOT EXISTS idx_billings_invoice_number ON billings(invoice_number);

-- ==========================================
-- 4. ROW LEVEL SECURITY (RLS) policies
-- ==========================================

-- Enable RLS
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE billings ENABLE ROW LEVEL SECURITY;

-- User Settings Policies
DROP POLICY IF EXISTS "Users can manage own settings" ON user_settings;
CREATE POLICY "Users can manage own settings" ON user_settings
  FOR ALL USING (
    (auth.uid()::text = user_id) OR 
    (auth.jwt() ->> 'email' = user_email) OR
    (current_setting('request.jwt.claims', true)::json->>'email' = user_email)
  )
  WITH CHECK (
    (auth.uid()::text = user_id) OR 
    (auth.jwt() ->> 'email' = user_email) OR
    (current_setting('request.jwt.claims', true)::json->>'email' = user_email)
  );

-- Contracts Policies
DROP POLICY IF EXISTS "Users can manage own contracts" ON contracts;
CREATE POLICY "Users can manage own contracts" ON contracts
  FOR ALL USING (
    (auth.jwt() ->> 'email' = user_email) OR
    (current_setting('request.jwt.claims', true)::json->>'email' = user_email)
  );

-- Companies Policies
DROP POLICY IF EXISTS "Users can manage own companies" ON companies;
CREATE POLICY "Users can manage own companies" ON companies
  FOR ALL USING (
    (auth.jwt() ->> 'email' = user_email) OR
    (current_setting('request.jwt.claims', true)::json->>'email' = user_email)
  );

-- Templates Policies
DROP POLICY IF EXISTS "Users can manage own templates" ON templates;
CREATE POLICY "Users can manage own templates" ON templates
  FOR ALL USING (
    (auth.jwt() ->> 'email' = user_email) OR
    (current_setting('request.jwt.claims', true)::json->>'email' = user_email)
  );

-- Billings Policies
DROP POLICY IF EXISTS "Users can manage own billings" ON billings;
CREATE POLICY "Users can manage own billings" ON billings
  FOR ALL USING (
    (auth.jwt() ->> 'email' = user_email) OR
    (current_setting('request.jwt.claims', true)::json->>'email' = user_email)
  );

-- ==========================================
-- 5. TRIGGERS
-- ==========================================

-- Update updated_at for user_settings
DROP TRIGGER IF EXISTS tr_user_settings_updated_at ON user_settings;
CREATE TRIGGER tr_user_settings_updated_at
BEFORE UPDATE ON user_settings
FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

-- Update updated_at for contracts
DROP TRIGGER IF EXISTS tr_contracts_updated_at ON contracts;
CREATE TRIGGER tr_contracts_updated_at
BEFORE UPDATE ON contracts
FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

-- Update updated_at for companies
DROP TRIGGER IF EXISTS tr_companies_updated_at ON companies;
CREATE TRIGGER tr_companies_updated_at
BEFORE UPDATE ON companies
FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

-- Update updated_at for billings
DROP TRIGGER IF EXISTS tr_billings_updated_at ON billings;
CREATE TRIGGER tr_billings_updated_at
BEFORE UPDATE ON billings
FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

