-- user_settings テーブルのみ作成（認証はNextAuth.jsのJWTで管理）

CREATE TABLE IF NOT EXISTS user_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email TEXT UNIQUE NOT NULL,
  gemini_api_key TEXT,
  google_client_id TEXT,
  google_api_key TEXT,
  google_drive_folder_id TEXT,
  party_b_info JSONB DEFAULT '{}'::jsonb,
  quick_access JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 契約書テーブル
CREATE TABLE IF NOT EXISTS contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  party_a TEXT NOT NULL,
  party_b TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '提案中',
  storage_path TEXT,
  auto_renewal BOOLEAN DEFAULT FALSE,
  deadline DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- インデックス作成
CREATE INDEX IF NOT EXISTS idx_contracts_user_email ON contracts(user_email);

-- ContractsのRLS有効化
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;

-- 全ユーザーが自分のメールアドレスに基づいてアクセス可能
CREATE POLICY "Users can manage own contracts" ON contracts
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');

-- Create companies table
CREATE TABLE IF NOT EXISTS companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  name TEXT NOT NULL,
  postal_code TEXT,
  address TEXT,
  building TEXT,
  president_title TEXT,
  president_name TEXT,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  position TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for companies
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;

-- Create policy for companies
CREATE POLICY "Users can manage own companies" ON companies
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');

-- Create templates table
CREATE TABLE IF NOT EXISTS templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email TEXT NOT NULL,
  name TEXT NOT NULL,
  party_a TEXT,
  party_b TEXT,
  address_a TEXT,
  address_b TEXT,
  president_position_a TEXT,
  president_name_a TEXT,
  president_position_b TEXT,
  president_name_b TEXT,
  content TEXT,
  saved_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for templates
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;

-- Create policy for templates
CREATE POLICY "Users can manage own templates" ON templates
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');

-- RLS有効化
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

-- 全ユーザーが自分のメールアドレスに基づいてアクセス可能
CREATE POLICY "Users can manage own settings" ON user_settings
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');
```
