-- Add missing columns to user_settings table
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS party_b_info JSONB DEFAULT '{}'::jsonb;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS quick_access JSONB DEFAULT '[]'::jsonb;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS google_client_id TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS google_api_key TEXT;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS google_drive_folder_id TEXT;

-- Ensure other tables exist (redundant if schema.sql was run, but safe)
CREATE TABLE IF NOT EXISTS contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  party_a TEXT NOT NULL,
  party_b TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '提案中',
  storage_path TEXT,
  auto_renewal BOOLEAN DEFAULT FALSE,
  deadline DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  name TEXT NOT NULL,
  postal_code TEXT,
  address TEXT,
  building TEXT,
  president_title TEXT,
  president_name TEXT,
  contact_person TEXT,
  email TEXT,
  phone TEXT,
  position TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email TEXT NOT NULL,
  name TEXT NOT NULL,
  party_a TEXT,
  party_b TEXT,
  address_a TEXT,
  address_b TEXT,
  president_position_a TEXT,
  president_name_a TEXT,
  president_position_b TEXT,
  president_name_b TEXT,
  content TEXT,
  saved_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for all tables (idempotent-ish commands or just ensuring they are enabled)
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;

-- Re-create policies to ensure they exist (DROP IF EXISTS first to avoid errors)
DROP POLICY IF EXISTS "Users can manage own settings" ON user_settings;
CREATE POLICY "Users can manage own settings" ON user_settings
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');

DROP POLICY IF EXISTS "Users can manage own contracts" ON contracts;
CREATE POLICY "Users can manage own contracts" ON contracts
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');

DROP POLICY IF EXISTS "Users can manage own companies" ON companies;
CREATE POLICY "Users can manage own companies" ON companies
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');

DROP POLICY IF EXISTS "Users can manage own templates" ON templates;
CREATE POLICY "Users can manage own templates" ON templates
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');
