-- Migration for AI Contract & Invoice Automation
-- Run this in your Supabase SQL Editor

-- 1. Add metadata column to contracts table
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS metadata JSONB;

-- 2. Create billings table
CREATE TABLE IF NOT EXISTS billings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id BIGINT REFERENCES contracts(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL,
  issue_date DATE,
  payment_deadline DATE,
  amount DECIMAL,
  tax_amount DECIMAL,
  status TEXT DEFAULT 'Planned', -- Planned, Approved, Sent, Paid
  pdf_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS for billings
ALTER TABLE billings ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policy for billings
CREATE POLICY "Users can manage own billings" ON billings
  FOR ALL USING (user_email = current_setting('request.jwt.claims', true)::json->>'email');

-- 5. Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_billings_contract_id ON billings(contract_id);
CREATE INDEX IF NOT EXISTS idx_billings_user_email ON billings(user_email);
